### ISSUE TITLE
The user is forced to close the modal window containing the solution to conduct game analysis

### ISSUE THREAD

**Issue by CTMarius** [Assios/chessguessr#23]
**Problem:**
In the current implementation the user needs to close the modal window containing the solution to view the board again in order to analyse the game. This implementation forces the user to write down the solution or memorise all moves before returning to the board.

The user experience could be improved by allowing the user to move the modal window, thus allowing the user to conduct a better analysis of the moves by comparing the solution with the board.

Other ideas that could improve the experience significantly: 

- opening the modal window in the right hand side of the board;
- displaying the solution in the main screen somewhere to the left side of the board;
- make the modal transparent when long clicked, thus displaying the board underneath.

**Comment by Assios** [comment]
The draggable window would have been a good fix if it didn't break on mobile, appreciate the issue and the PR!

It is possible to follow the link to the game on Lichess, where you can see the current position, the continuation, and also play around with the pieces. Would this work?

**Comment by CTMarius** [comment]
Yeah, it will work for most users. This is more of a personal preference than a real issue, it came up from the fact that I didn't like being redirected to the Lichess interface, mainly because it's a poorer interface compared to the chessguessr one. It takes me a while to get used to the switch and make sense of the Lichess interface and found it faster just to imagine the moves on the chessguessr board. 

I also noticed that whenever I fail a puzzle and can't replay the solution on the same interface, I give up on trying to view the solution in Lichess. I'm not sure if other users are experiencing the same, I assume most people are ok with the Lichess redirect. 

In any case thanks for taking a look at the PR, I really appreciate what you're doing.

**Comment by Assios** [comment]
I see, thanks for the feedback. I'll see if I can find a fix for this.

**Comment by olagjo** [comment]
Agree with the problem statement! I also often just want to figure out "what was the one move I missed" without going somewhere else entirely 😅 

Several suggestions for possible solutions:
- Also show the correct line somewhere on the page behind the modal (i.e. to keep it visible after modal is closed)
  - With this fix, the correct solution could even be clickable, i.e. clicking on one of the tiles from the solution takes the board to the state when that move has just been done
- Keep the board playable after you have spent all of your attempts (so if the solution is visible, you can actually play it out manually)
