### ISSUE TITLE
Error loading site

### ISSUE THREAD

**Issue by bryan0** [Assios/chessguessr#31]
“Error

Cannot read properties of undefined (reading 'id')
If this error persists, please [file an issue](https://github.com/Assios/chessguessr/issues) on Github or [contact Assios on Lichess](https://lichess.org/inbox/Assios).”

**Comment by Assios** [comment]
Fixed now! I forgot to add today's game.

**Comment by dolmas1** [comment]
Just FYI I'm getting an identical error this morning (I assume for the same reason?).

Thanks so much for maintaining this btw, it's great fun :)
