### ISSUE TITLE
incorrect lichess link for game 2022-11-13

### ISSUE THREAD

**Issue by szamanr** [Assios/chessguessr#39]
go to: https://www.chessguessr.com/games/145
solving the puzzle takes you to https://lichess.org/56zqiMBS/black#85

expected position:
`r5k1/2b2rpp/2p1b2P/p3p3/p1q1Pn2/B1P2NQ1/1PB5/2KRR3 w - - 0 1`

actual position:
`8/4Npk1/2qp2p1/R3p3/1P2P3/2PQ1P1p/6PK/2r5 b - - 0 43`

**Comment by Assios** [comment]
Thanks, fixed by d1ffc85
