### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by jellyedwards** [Assios/chessguessr#41]
Hi, first of all thanks so much for this! I wish I had 5 goes to make a move in real life chess :D

After a few weeks with no problems, I've started to get an Application Error

![Screenshot_2022-12-08-06-08-59-860_com brave browser](https://user-images.githubusercontent.com/14051992/206371391-745a0402-6745-47ea-ae06-2e15919ecced.jpg)

I can't dismiss the dialog when this happens.

I'm using Brave on Android, it doesn't happen in an incognito window or in another browser, but it keeps happening in Brave even when I remove all site data.

Thanks!

**Comment by ktakats** [comment]
Hi, I've been having the exact same issue in the last few days, on an android phone using Chrome browser.

**Comment by Assios** [comment]
Thanks for the bug report! I will look into it, but I haven't been able to reproduce it yet, as I don't have an android phone.

**Comment by mysterysquared** [comment]
Clearing cache and cookies fixed this for me (at the cost of my stats 🙂)
