### ISSUE TITLE
Wrong color

### ISSUE THREAD

**Issue by unrealwill** [Assios/chessguessr#46]
On today's problem : GM Simon Williams (2461) – WIM Anastasiya Rakhmangulova (2266) 
https://lichess.org/1Tr0gZQo 
Notice how Nxd4 appears two times :
The solution was : Rxb7 Nxd4 Nxd4 Bxa4 Nxe6
I proposed           : Rxb7 Nxd4 Rxd7 Qxd7 Nxd4

The first Nxd4 was correctly green but the second Nxd4 was colored blue only, instead of blue/orange, which made me explicitly avoid the correct solution.

At the time of writing the link below to share this game seems also wrong : https://www.chessguessr.com/games/127 which points to : GM Magnus Carlsen (2856) – GM Vladimir Fedoseev (2688)

**Comment by compguy284** [comment]
`discardYellowArray[solutionArray.indexOf(move.move)] = null;`
the above line in app/hooks/useChessguessr.ts is preventing the "blue/yellow" combo from being shown as seen in the examples below.

with mentioned line uncommented.
![2023-07-02T01:17:17,729718394-04:00](https://github.com/Assios/chessguessr/assets/33595667/c24cd343-90cd-4a8a-af4c-04cae1ba712a)

with mentioned line commented.
![2023-07-02T01:24:20,291460358-04:00](https://github.com/Assios/chessguessr/assets/33595667/6319c5f2-c30c-4ee3-bd8a-1758b70cbff3)

**Comment by Assios** [comment]
Thanks @unrealwill and @compguy284. Fixed in #54.
