### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by hdkc** [Assios/chessguessr#51]
When I went to chessguessr this morning, I got the following error message :

Error
Cannot read properties of undefined (reading 'id')

If this error persists, please [file an issue](https://github.com/Assios/chessguessr/issues) on Github or [contact Assios on Lichess](https://lichess.org/inbox/Assios).

**Comment by Assios** [comment]
Thanks for the report, forgot to add today's game. Fixed now :)

**Comment by JanRomero** [comment]
@Assios this seems to be back right now

**Comment by Assios** [comment]
@JanRomero Fixed!

**Comment by Assios** [comment]
@JanRomero No worries, I appreciate the comment, as I had forgotten to commit today's game :)
