### ISSUE TITLE
"Unexpected Server Error" when accessing the site

### ISSUE THREAD

**Issue by TheBooker66** [Assios/chessguessr#67]
I tried opening the site today and got a screen which read "Error; Unexpected Server Error; If this error persists, please file an issue on Github or contact Assios on Lichess.". I tried again after an hour and got the same error. I tested in both Opera GX and Microsoft Edge and got the same error.

**Comment by Assios** [comment]
Thanks for the report. I had forgotten to add the game for the day. Fixed.

**Comment by TheBooker66** [comment]
It seems you've forgotten again.

**Comment by groszdaniel** [comment]
Again.

**Comment by groszdaniel** [comment]
And again.

**Comment by Assios** [comment]
Haha thanks, fixing.
